import Header from "@/widgets/Header";
import "../styles/global.css";
import "highlight.js/styles/atom-one-light.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import GoogleAnalytics from "@/shared/lib/GoogleAnalytics";

const gaId = process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID ?? null;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>{gaId && <GoogleAnalytics gaId={gaId} />}</head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header />
        <main className="main">{children}</main>
      </body>
    </html>
  );
}
